/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lex;

import javax.swing.JTextArea;

/**
 *
 * @author carlo
 */
public class codigo extends javax.swing.JFrame {

        
    /**
     * Creates new form codigo
     */
    public codigo() {
        
        initComponents();
                       compilador c = new compilador();
                 jTextArea1.setText("    LIST  P=16F886\n" +
"    include <P16f886.INC>\n" +
"   \n" +
"    __config _CONFIG1, 0x2CF4   \n" +
"    __config _CONFIG2, 0x0700\n" +
"    \n" +
"    ORG 0x00\n" +
"    \n ;---CONFIGURACION DE ENTRADAS Y SALIDAS--- \n\n" +
"	BANKSEL PORTA \n" +
"    CLRF PORTA \n" +
"    BANKSEL TRISA \n" +
"    MOVLW B'11111111' \n" +
"    MOVWF TRISA\n" +
"    BANKSEL PORTA\n" +
"\n" +
"    BANKSEL PORTB \n" +
"    CLRF PORTB \n" +
"    BANKSEL TRISB \n" +
"    MOVLW B'00000000'\n" +
"    MOVWF TRISB\n" +
"    BANKSEL PORTB\n\n ;--- DECLARACION DE VARIABLES --- \n"
                +"GOTO BUCLE\nINCLUDE <RETARDOS_8MHZ.inc>\n    END");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("    LIST  P=16F886\n    include <P16f886.INC>\n   \n    __config _CONFIG1, 0x2CF4   \n    __config _CONFIG2, 0x0700\n    \n    ORG 0x00\n    \n ;---CONFIGURACION DE ENTRADAS Y SALIDAS--- \n\n\tBANKSEL PORTA \n    CLRF PORTA \n    BANKSEL TRISA \n    MOVLW B'11111111' \n    MOVWF TRISA\n    BANKSEL PORTA\n\n    BANKSEL PORTB \n    CLRF PORTB \n    BANKSEL TRISB \n    MOVLW B'00000000'\n    MOVWF TRISB\n    BANKSEL PORTB\n\n ;--- DECLARACION DE VARIABLES --- \nGOTO BUCLE\nINCLUDE <RETARDOS_8MHZ.inc>\n    END");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Codigo Objeto en ASM Creado por FCC Compiler");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
