
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 29 13:13:34 CST 2017
//----------------------------------------------------

package lex;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RETARDO = 20;
  public static final int DIVISION = 55;
  public static final int READ = 67;
  public static final int PENTRADA = 8;
  public static final int MENORIGUALQUE = 32;
  public static final int VERDADERO = 6;
  public static final int UNTIL = 60;
  public static final int MOTORELECT = 15;
  public static final int INICIO = 23;
  public static final int NEGACION = 40;
  public static final int SERVO = 19;
  public static final int FALSO = 7;
  public static final int DECLARA = 2;
  public static final int ALTO = 25;
  public static final int NOT = 72;
  public static final int COMPARA = 14;
  public static final int MOSTRARMENSAJE = 61;
  public static final int TIEMPO = 24;
  public static final int MENORQUE = 33;
  public static final int ERROR = 64;
  public static final int FINAL = 22;
  public static final int THEN = 42;
  public static final int LLAVEIZQ = 4;
  public static final int SAR = 16;
  public static final int CICLO = 13;
  public static final int EF = 12;
  public static final int COMA = 37;
  public static final int ED = 11;
  public static final int MAYORIGUALQUE = 31;
  public static final int MODULO = 73;
  public static final int IGUAL = 35;
  public static final int DETENER = 18;
  public static final int WHILE = 47;
  public static final int PAREDER = 50;
  public static final int DOSPUNTOS = 51;
  public static final int PUNTOYCOMA = 30;
  public static final int Y = 38;
  public static final int DO = 46;
  public static final int VARIABLE = 29;
  public static final int FOR = 44;
  public static final int ELSE = 43;
  public static final int O = 39;
  public static final int PROCEDURE = 48;
  public static final int INTEGERNUM = 56;
  public static final int EOF = 0;
  public static final int PUNTO = 62;
  public static final int SUMA = 52;
  public static final int CARACTER = 27;
  public static final int REPEAT = 59;
  public static final int PSALIDA = 9;
  public static final int OR = 70;
  public static final int error = 1;
  public static final int GATO = 68;
  public static final int RESTA = 54;
  public static final int ENTRADA = 10;
  public static final int IF = 41;
  public static final int CONTADOR = 21;
  public static final int ID = 57;
  public static final int MAYORQUE = 34;
  public static final int OF = 66;
  public static final int MULTIPLICACION = 53;
  public static final int CASE = 65;
  public static final int CADENA = 58;
  public static final int BOLEANO = 28;
  public static final int CAR = 17;
  public static final int DISTINTODE = 36;
  public static final int AND = 71;
  public static final int TO = 45;
  public static final int LLAVEDER = 5;
  public static final int PAREIZQ = 49;
  public static final int PROGRAMA = 69;
  public static final int BUCLE = 3;
  public static final int SALIDA = 63;
  public static final int CAD = 26;
}

